docs(base): Readthedocs ImageMagick badge failure
I can't reproduce this issue locally but I was able to reproduce it using:

    $ docker run -it --rm -v "./:/usr/local/src/project-structure/" "ubuntu:22.04"
    # apt update && apt install -y python3-pip imagemagick
    # pip3 install -r ./requirements/build.txt.in
    # cd /usr/local/src/project-structure/docs/
    # python3 -m "sphinx" -T -E -b "latex" -d "_build/doctrees" -D language="en" "." \
    > "../build/docs/pdf"
      File "/usr/lib/python3.10/subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['convert', '/usr/local/src/project-structure/docs/_build/doctrees/images/73d57933d8bc4bf5473eca5bd0d0a28f07e73043/rpatterson.svg[0]', '/usr/local/src/project-structure/docs/_build/doctrees/images/rpatterson1.png']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/sphinx/cmd/build.py", line 298, in build_main
        app.build(args.force_all, args.filenames)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/application.py", line 355, in build
        self.builder.build_update()
      File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/__init__.py", line 290, in build_update
        self.build(['__all__'], to_build)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/__init__.py", line 363, in build
        self.write(docnames, list(updated_docnames), method)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/latex/__init__.py", line 299, in write
        doctree = self.assemble_doctree(
      File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/latex/__init__.py", line 365, in assemble_doctree
        self.env.resolve_references(largetree, indexfile, self)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/environment/__init__.py", line 676, in resolve_references
        self.apply_post_transforms(doctree, fromdocname)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/environment/__init__.py", line 688, in apply_post_transforms
        transformer.apply_transforms()
      File "/usr/local/lib/python3.10/dist-packages/sphinx/transforms/__init__.py", line 83, in apply_transforms
        super().apply_transforms()
      File "/usr/local/lib/python3.10/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
        transform.apply(**kwargs)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/transforms/post_transforms/images.py", line 33, in apply
        self.handle(node)
      File "/usr/local/lib/python3.10/dist-packages/sphinx/transforms/post_transforms/images.py", line 253, in handle
        if self.convert(abs_srcpath, destpath):
      File "/usr/local/lib/python3.10/dist-packages/sphinx/ext/imgconverter.py", line 71, in convert
        raise ExtensionError(__('convert exited with error:\n'
    sphinx.errors.ExtensionError: convert exited with error:
    [stderr]
    b"convert-im6.q16: unrecognized color `d5d5d5' @ warning/color.c/GetColorCompliance/1057.\nconvert-im6.q16: non-conforming drawing primitive definition `stroke' @ error/draw.c/RenderMVGContent/4404.\n"
    [stdout]
    b''

    Extension error:
    convert exited with error:
    [stderr]
    b"convert-im6.q16: unrecognized color `d5d5d5' @ warning/color.c/GetColorCompliance/1057.\nconvert-im6.q16: non-conforming drawing primitive definition `stroke' @ error/draw.c/RenderMVGContent/4404.\n"
    [stdout]
    b''
    Running Sphinx v7.2.6
    matplotlib is not installed, social cards will not be generated
    building [mo]: targets for 0 po files that are out of date
    building [latex]: all documents
    updating environment: [new config] 4 added, 0 changed, 0 removed
    looking for now-outdated files... none found
    copying TeX support files...
    index
    resolving references...

    ====================== slowest reading durations =======================
    0.042 index
    0.015 contributing
    0.007 todo
    0.001 news

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/sphinx/ext/imgconverter.py", line 63, in convert
        subprocess.run(args, capture_output=True, check=True)

Inspecting the involved build artifacts I confirmed that it was the GitHub
`rpatterson?style=social` badge.  I confirmed that turning that badge into a `*.png`
image directly with `rpatterson.png?style=social`, thus skipping conversion at all,
resolved the issue.  I never, however, liked the `social` style and thought it was my
only option.  Switch to the same style as the rest of the badges which also resolves the
issue.