build(py-docker): Wrong devel image tox install
    :3+ docker compose run --rm -T project-structure-devel make -e ./.tox/py311/.tox-info.json
    Adding group `project-structure' (GID 1000) ...
    Done.
    adduser: The home directory `/home/project-structure' already exists.  Not touching this directory.
    adduser: Warning: The home directory `/home/project-structure' does not belong to the user you are currently creating.
    GNU Make 4.3
    Built for x86_64-pc-linux-gnu
    Copyright (C) 1988-2020 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    Reading makefiles...
    Reading makefile 'Makefile'...
    Reading makefile '.env' (search path) (no ~ expansion)...
    Updating makefiles....
     Considering target file '.env'.
      Looking for an implicit rule for '.env'.
      No implicit rule found for '.env'.
      Finished prerequisites of target file '.env'.
     No need to remake target '.env'.
     Considering target file 'Makefile'.
      Looking for an implicit rule for 'Makefile'.
      No implicit rule found for 'Makefile'.
      Finished prerequisites of target file 'Makefile'.
     No need to remake target 'Makefile'.
    Updating goal targets....
    Considering target file '.tox/py311/.tox-info.json'.
      Considering target file '/home/project-structure/.local/bin/tox'.
       File '/home/project-structure/.local/bin/tox' does not exist.
        Considering target file '/home/project-structure/.local/bin/pipx'.
          Considering target file '/usr/local/bin/pip3'.
           Finished prerequisites of target file '/usr/local/bin/pip3'.
          No need to remake target '/usr/local/bin/pip3'.
         Finished prerequisites of target file '/home/project-structure/.local/bin/pipx'.
         Prerequisite '/usr/local/bin/pip3' is older than target '/home/project-structure/.local/bin/pipx'.
        No need to remake target '/home/project-structure/.local/bin/pipx'.
       Finished prerequisites of target file '/home/project-structure/.local/bin/tox'.
      Must remake target '/home/project-structure/.local/bin/tox'.
    Putting child 0x5562dde62290 (/home/project-structure/.local/bin/tox) PID 91 on the chain.
    Live child 0x5562dde62290 (/home/project-structure/.local/bin/tox) PID 91
    :1+ pipx install --python python3.11 tox
    Traceback (most recent call last):
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 766, in setup_log_file
        return _setup_log_file()
               ^^^^^^^^^^^^^^^^^
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 759, in _setup_log_file
        log_file.touch()
      File "/usr/local/lib/python3.11/pathlib.py", line 1108, in touch
        fd = os.open(self, flags, mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    PermissionError: [Errno 13] Permission denied: '/home/project-structure/.local/state/pipx/log/cmd_2023-12-09_11.00.35.log'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/project-structure/.local/bin/pipx", line 8, in <module>
        sys.exit(cli())
                 ^^^^^
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 880, in cli
        setup(parsed_pipx_args)
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 820, in setup
        setup_logging("verbose" in args and args.verbose)
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 773, in setup_logging
        pipx.constants.pipx_log_file = setup_log_file()
                                       ^^^^^^^^^^^^^^^^
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 768, in setup_log_file
        return _setup_log_file(platformdirs.user_log_path("pipx"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/project-structure/.local/lib/python3.11/site-packages/pipx/main.py", line 759, in _setup_log_file
        log_file.touch()
      File "/usr/local/lib/python3.11/pathlib.py", line 1108, in touch
        fd = os.open(self, flags, mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    PermissionError: [Errno 13] Permission denied: '/home/project-structure/.local/state/pipx/log/cmd_2023-12-09_11.00.35.log'
    Reaping losing child 0x5562dde62290 PID 91
    Removing child 0x5562dde62290 PID 91 from chain.
    make: *** [Makefile:1319: /home/project-structure/.local/bin/tox] Error 1
    Reaping losing child 0x55994df12620 PID 1753986
    make: *** [Makefile:1076: var-docker/debian-py311/.tox/py311/.tox-info.json] Error 2